### ISSUE TITLE
HOVER buttons don't have a hover action

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit-site#8]
Some of the buttons in the docs say "HOVER", but they don't have a hover action, and they are actually clickable buttons. For example, the two "HOVER" buttons in https://getuikit.com/docs/drop#usage .

(I think I saw one or two other cases of this -- you might want to grep the docs for all buttons with "Hover" in their text.)

**Comment by janschoenherr** [comment]
I believe this has been resolved, thanks.

**Comment by lukehutch** [comment]
@janschoenherr This is still not resolved for me. Hovering over the "HOVER" buttons does not cause the menu to pop up.

**Comment by janschoenherr** [comment]
Are you still using Chrome? Is it a touch device?

**Comment by lukehutch** [comment]
Yes, this is Chrome on Linux, desktop (not touch).

**Comment by janschoenherr** [comment]
Did you clear your browser cache?

**Comment by lukehutch** [comment]
I just tried that, and it didn't change the behavior.

I looked at the resources being loaded, and I see "theme.css?141". I assume the "?141" part is supposed to get bumped every time there's a code checkin, and that browsers are not supposed to cache if URL query parameters change? (Why not use an SHA1 hash instead of a number?)

**Comment by janschoenherr** [comment]
Can you try in another browser?

**Comment by lukehutch** [comment]
Sure it's also not working in Firefox and Vivaldi (which is based on Blink, so the behavior in Vivaldi is likely to match the Chrome behavior). (Both are on the same Linux desktop machine.)

**Comment by janschoenherr** [comment]
Could you please give it another try, is it working for you now?

**Comment by lukehutch** [comment]
@janschoenherr Solved for me in Chrome on Linux.Thanks!
